esphome:
  name: esp32blegw
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "YOUR_WIFI_NET_NAME"
  password: "YOUR_WIFI_PASSWORD"

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32blegw Hotspot"
    password: "d-diot.com"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# BLE config (see the log to find the MAC address of your BLE devices)
esp32_ble_tracker:


# Fan configuration
switch:
  - platform: gpio
    pin: GPIO15
    name: "Fan"
    id: "fan_1"
    internal: false
    icon: "mdi:fan"


# Dallas temperature sensor
dallas:
  - pin: GPIO4
    update_interval: 180s
    id: "dallas_1"


sensor:
# Wifi signal monitor
  - platform: wifi_signal
    name: "ESP32-BLE-GW WiFi Signal"
    update_interval: 60s
# Dallas temperature sensor
  - platform: dallas
    index: 0
    name: "d-diot hub int. temp."
    id: "temp_1"
    dallas_id: "dallas_1"
    on_value_range:
      - above: 45
        then:
          - switch.turn_on: fan_1
      - below: 45
        then:
          - switch.turn_off: fan_1
# Example BLE sensor, see https://esphome.io/components/esp32_ble_tracker.html 
#  - platform: ble_rssi
#    mac_address: XX:YY:ZZ:AA:BB:CC
#    name: "Your device name"


# Example BLE sensor, see https://esphome.io/components/esp32_ble_tracker.html
#binary_sensor:
# BLE devices example
#  - platform: ble_presence
#    mac_address: XX:YY:ZZ:AA:BB:CC
#    name: "Your device name"
